name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ShellCheck for scripts
        uses: ludeeus/action-shellcheck@v1
        with:
          files: scripts/setup.sh
      - name: Dockerfile Lint
        uses: redcoolbeans/dockerlint-action@v1
        with:
          directories: |
            docker/node1
            docker/node2
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build node1 Docker image
        run: docker build -t bitgo-node1 docker/node1
      - name: Build node2 Docker image
        run: docker build -t bitgo-node2 docker/node2