name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ShellCheck for scripts
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          path: scripts/setup.sh
      - name: Dockerfile Lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/node1/Dockerfile
      - name: Dockerfile Lint (node2)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/node2/Dockerfile
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build node1 Docker image
        run: docker build -t bitgo-node1 docker/node1
      - name: Build node2 Docker image
        run: docker build -t bitgo-node2 docker/node2
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and start containers
        run: docker-compose up --build -d
      - name: Wait for nodes and run setup script
        run: bash scripts/setup.sh
      - name: Show logs
        run: docker-compose logs